### ISSUE TITLE
Storing journal articles in repo: Instead of the file, simply provide the URL to it

### ISSUE THREAD

**Issue by lwjohnst86** [steno-aarhus/epi-stats#11]
Related to @HenrikStovring great question during the meeting. I don't think it will be an issue to store the files on the repo. However, you never know. And in fact, I don't see why we need the articles here anyway, when we can provide the link to the article instead. That would save us a little bit of effort in not having to upload pdf files and it would make it easier to visually link the article on the webpage (there's some neat things you can do with it :grin:). Once I make the template, I'll go through and remove the PDFs and add their URLs to the session's `index.qmd` file.

**Comment by HenrikStovring** [comment]
Thanks Luke - that is a wise suggestion. And it will even make the Journals happier as it creates traffic to their sites.


Best Henrik

________________________________
Fra: Luke W Johnston ***@***.***>
Sendt: 23. november 2023 11:09:18
Til: steno-aarhus/epi-stats
Cc: Henrik Støvring; Mention
Emne: [steno-aarhus/epi-stats] Storing journal articles in repo: Instead of the file, simply provide the URL to it (Issue #11)


Related to @HenrikStovring<https://github.com/HenrikStovring> great question during the meeting. I don't think it will be an issue to store the files on the repo. However, you never know. And in fact, I don't see why we need the articles here anyway, when we can provide the link to the article instead. That would save us a little bit of effort in not having to upload pdf files and it would make it easier to visually link the article on the webpage (there's some neat things you can do with it 😁). Once I make the template, I'll go through and remove the PDFs and add their URLs to the session's index.qmd file.

**Comment by lwjohnst86** [comment]
@HenrikStovring I've updated the website! It actually has stuff now :laughing: I also removed the articles and instead you can add the reference details to the top header of the file to cite it in the post.
